export { default as MagisterClient } from "./client/MagisterClient";
export type {
    Account,
    AppointmentAttachment,
    AppointmentAttachmentLink,
    AppointmentDetail,
    AssignmentDetail,
    AssignmentItem,
    Contact,
    Enrollment,
    GradeColumn,
    GradeItem,
    ScheduleItem,
    MessageAttachment,
    MessageAttachmentRef,
    MessageDetail,
    MessageItem,
    MessageRecipient,
    MessageRecipientRef,
    MessageSender,
    MessageWithAttachments,
    SendMessagePayload,
    Session,
    StudyGuideDetail,
    StudyGuideFile,
    StudyGuideItem,
    StudyGuidePart,
    StudyGuidePartDetail,
    Tokens,
    UploadedAttachment,
} from "./types";
export type {
    GetMessagesOptions,
    SearchContactsOptions,
    UploadBody,
    UploadFileOptions,
} from "./resources/messages";
